name: Build and Push Docker Image
on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  secret_scanning:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --results=verified,unknown
  
  parellel_job_test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Testing parellel job with one step in it."
  
  build_push_docker:
    needs: secret_scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
      
      # - name: Scan Image
      #   uses: anchore/scan-action@v3
      #   id: scan
      #   with:
      #     image: ${{ steps.meta.outputs.tags }}
      #     fail-build: true
      #     output-format: sarif
  
      # - name: Upload Anchore Scan SARIF Report
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Prepare Trivy Image Reference
        run: |
          echo "TRIVY_IMAGE_REF=docker.io/${{ fromJSON(steps.meta.outputs.tags) }}" >> $GITHUB_ENV
          echo "---"
          echo "docker.io/${{ fromJSON(steps.meta.outputs.tags) }}"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "${{ env.TRIVY_IMAGE_REF }}"
          format: 'sarif'
          output: 'trivy-results.sarif'
        env:
          TRIVY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
