name: Scan for Secrets
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: 
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install TruffleHog
        run: pip install trufflehog

      - name: Scan for secrets
        run: trufflehog -r .
        if: steps.scan-for-secrets.exit_code != 0
